"use client";
import "./globals.css";
import "./prism.css";

import { useEffect, useState } from "react";

import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";

import { allAws, allCsses } from "@/.contentlayer/generated";
import {
  icon_arrow_right,
  icon_menu,
  icon_moon,
  icon_search,
  icon_sun,
} from "@/assets";

/** use 쓸 때 메타데이터 쓰면 에러 */
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [mount, setMount] = useState(false); // 마운트 유무
  const [theme, setTheme] = useState(false); // 다크모드, 라이트모드
  const [menuActive, setMenuActive] = useState(false); // 모바일 메뉴 활성화 유무

  const all = [allCsses, allAws].sort((a: any, b: any): number => {
    const upperCaseA = a[0].type.toUpperCase();
    const upperCaseB = b[0].type.toUpperCase();

    if (upperCaseA > upperCaseB) return 1;
    if (upperCaseA < upperCaseB) return -1;
    return 0;
  }); // 모든 포스트

  const [dirAcitve, setDirActive] = useState(new Array(all.length).fill(false)); // 디렉토리 활성화 유무

  /** 디렉토리 활성화 핸들러 */
  const listDirActiveHandler = (num: number) => {
    dirAcitve[num] = !dirAcitve[num];
    setDirActive([...dirAcitve]);
  };

  /** 마운트 되면 true */
  useEffect(() => {
    setMount(true);
    console.log(all);
  }, []);

  /** theme 값에 따라 light, dark */
  // TODO: 사용자 선호 모드 찾아서 로컬스토리지에 저장 후 그 값 참조해서 모드 할당
  useEffect(() => {
    theme
      ? document.documentElement.classList.remove("dark")
      : document.documentElement.classList.add("dark");
  }, [theme]);

  const path = usePathname(); // 라우팅 될 때 마다 url

  return (
    <html lang="en">
      <body
        className={`flex pl-[280px] md1000:pl-0 ${
          !mount && "opacity-0"
        }  ease-in-out duration-200`}
      >
        {/** 사이드바 데스크탑 */}
        <div className="fixed left-0 p-[12px] w-[280px] h-screen border-r-[1px] border-r-black md1000:hidden">
          <div className="flex items-center justify-between mb-3">
            <Link href={"/"}>
              <h1 className="font-bold text-xl">Joseph.log</h1>
            </Link>
            {/** 버튼 - 라이트, 다크 모드 */}
            <button
              className="flex items-center justify-center w-[22px] h-[22px] rounded-[100px] bg-gray-200 dark:bg-gray-800  ease-in-out duration-200"
              onClick={() => setTheme(!theme)}
            >
              <Image
                src={icon_sun}
                alt="icon_sun"
                width={16}
                height={16}
                className="dark:opacity-0"
              />
              <Image
                src={icon_moon}
                alt="icon_moon"
                width={16}
                height={16}
                className="absolute opacity-0 dark:opacity-100"
              />
            </button>
          </div>
          {/** 검색 - 추후 구현 */}
          <div className="flex mb-3 px-[7px] w-full h-8 border-[1px] border-gray-200 rounded-[4px]">
            <Image src={icon_search} alt="icon_search" width={18} height={18} />
            <input
              type="text"
              placeholder="Search..."
              className="px-[10px] w-full text-[14px] focus:outline-none
              placeholder:text-gray-400 placeholder:text-[14px]"
            />
          </div>
          {/** 메뉴 */}
          <div className="text-[14px] cursor-default">
            {all.map((el, num) => {
              return (
                <div
                  key={`list${num}`}
                  className={
                    dirAcitve[num]
                      ? `ease-in-out duration-200
                      h-[${(el.length + 1) * 32}px] overflow-hidden`
                      : " ease-in-out duration-200 h-[32px] overflow-hidden"
                  }
                >
                  <div
                    className="flex gap-[4px] pl-[2px] h-[32px] rounded-[4px] hover:bg-gray-100"
                    onClick={() => listDirActiveHandler(num)}
                  >
                    <Image
                      src={icon_arrow_right}
                      alt="icon_arrow"
                      width={14}
                      height={14}
                      className={
                        dirAcitve[num]
                          ? "ease-in-out duration-200 rotate-90"
                          : "ease-in-out duration-200 rotate-0"
                      }
                    />

                    <span className="font-semibold leading-7">
                      {`${el[0]._raw.sourceFileDir}`}
                    </span>
                  </div>

                  {el.map((post, j) => {
                    return (
                      <Link
                        href={post.url}
                        key={`${j}asba`}
                        className="cursor-default"
                      >
                        <div
                          className={`ml-[8px] flex items-center h-[30px] border-l-2 border-gray-200 hover:border-light-purple ${
                            path === post.url && "border-light-purple"
                          }`}
                        >
                          <div
                            className={`ml-[2px] pl-[8px] w-full h-[28px] overflow-hidden text-ellipsis text-nowrap leading-7 rounded-[4px] hover:bg-gray-100 ${
                              path === post.url &&
                              "text-light-purple bg-gray-100"
                            }`}
                          >{`${post.title}`}</div>
                        </div>
                      </Link>
                    );
                  })}
                </div>
              );
            })}
          </div>
        </div>

        {/** 사이드바 모바일 */}
        <div
          className={`hidden fixed left-0 overflow-hidden p-[12px] w-full border-r-[1px] border-r-black bg-white 
         duration-200 ease-in-out
        md1000:block ${menuActive ? "h-screen" : "h-[52px]"}`}
        >
          <div className="flex items-center justify-between mb-3">
            <Link href={"/"}>
              <h1 className="font-bold text-xl">Joseph.log</h1>
            </Link>
            {/** 버튼 - 라이트, 다크 모드 */}
            <div className="flex items-center gap-[8px]">
              <button
                className="flex items-center justify-center w-[20px] h-[20px] rounded-[100px] bg-gray-200 dark:bg-gray-800 ease-in-out duration-200"
                onClick={() => setTheme(!theme)}
              >
                <Image
                  src={icon_sun}
                  alt="icon_sun"
                  width={14}
                  height={14}
                  className="dark:opacity-0"
                />
                <Image
                  src={icon_moon}
                  alt="icon_moon"
                  width={14}
                  height={14}
                  className="absolute opacity-0 dark:opacity-100"
                />
              </button>
              <button onClick={() => setMenuActive(!menuActive)}>
                <Image src={icon_menu} alt="icon_menu" width={28} height={28} />
              </button>
            </div>
          </div>
          {/** 검색 - 추후 구현 */}
          <div className="flex mb-3 px-[7px] w-full h-8 border-[1px] border-gray-200 rounded-[4px]">
            <Image src={icon_search} alt="icon_search" width={18} height={18} />
            <input
              type="text"
              placeholder="Search..."
              className="px-[10px] w-full text-[14px] focus:outline-none
              placeholder:text-gray-400 placeholder:text-[14px]"
            />
          </div>
          {/** 메뉴 */}
          <div className="text-[14px] cursor-default">
            {all.map((el, num) => {
              return (
                <div
                  key={`list${num}`}
                  className={
                    dirAcitve[num]
                      ? `ease-in-out duration-200
                      h-[${(el.length + 1) * 32}px] overflow-hidden`
                      : " ease-in-out duration-200 h-[32px] overflow-hidden"
                  }
                >
                  <div
                    className="flex gap-[4px] pl-[2px] h-[32px] rounded-[4px] hover:bg-gray-100"
                    onClick={() => listDirActiveHandler(num)}
                  >
                    <Image
                      src={icon_arrow_right}
                      alt="icon_arrow"
                      width={14}
                      height={14}
                      className={
                        dirAcitve[num]
                          ? "ease-in-out duration-200 rotate-90"
                          : "ease-in-out duration-200 rotate-0"
                      }
                    />

                    <span className="font-semibold leading-7">
                      {`${el[0].type}`}
                    </span>
                  </div>

                  {el.map((post, j) => {
                    return (
                      <Link
                        href={post.url}
                        key={`${j}asba`}
                        className="cursor-default"
                        onClick={() => setMenuActive(!menuActive)}
                      >
                        <div
                          className={`ml-[8px] flex items-center h-[30px] border-l-2 border-gray-200 hover:border-light-purple ${
                            path === post.url && "border-light-purple"
                          }`}
                        >
                          <div
                            className={`ml-[2px] pl-[8px] w-full h-[28px] overflow-hidden text-ellipsis text-nowrap leading-7 rounded-[4px] hover:bg-gray-100 ${
                              path === post.url &&
                              "text-light-purple bg-gray-100"
                            }`}
                          >{`${post.title}`}</div>
                        </div>
                      </Link>
                    );
                  })}
                </div>
              );
            })}
          </div>
        </div>
        {/** main content */}
        <main className="markdown mx-auto pt-[46px] px-[20px] w-[720px] overflow-hidden md1000:max-w-[720px] md1000:pt-[56px]">
          {children}
        </main>
      </body>
    </html>
  );
}
